### ISSUE TITLE
dag_config_get_uint32_attribute_ex in Linux 2.6.32-358.23.2.el6.x86_64

### ISSUE THREAD

**Issue by semkin** [the-tcpdump-group/libpcap#1144]
I compiled libpcap-1.10.1 in Linux 2.6.32-358.23.2.el6.x86_64
When I link with this library I get message 
libpcap.so: undefined reference to `dag_config_get_uint32_attribute_ex'

I see this in pcap-dag.c source code :
      if ((dag_error = dag_config_get_uint32_attribute_ex(pd->dag_ref, pd->drop_attr, &stream_drop)) == kDagErrNone) {

But can't find any other reference to dag_config_get_uint32_attribute_ex. Not in any header file

I don't have problem when compile in Linux 2.7 

Where is dag_config_get_uint32_attribute_ex, if it exists, in Linux 2.6 ?

**Comment by infrastation** [comment]
Most likely the C function is not in Linux because it is a part of the libpcap module specific to Endace DAG packet capture cards. If you do not have the DAG API and did not request libpcap to use it, it ought to default to the generic Linux-specific module instead of DAG. If the latter didn't work due to a Linux system problem or a libpcap problem, the expected style of build failure would be an error message from the build system before the compilation rather than a linker error after compiling a wrong file.

Please post exact steps to reproduce this issue including all progress messages and find a way to tell whether `CONFIG_PACKET_MMAP` is enabled in the kernel that you are trying to use (this should be in `/boot/config-2.6.32-358-x86_64` or a similarly named text file).

**Comment by guyharris** [comment]
> Where is dag_config_get_uint32_attribute_ex, if it exists, in Linux 2.6 ?

Nowhere.

It's in the library that Endace provides for their DAG network traffic capture cards.

Apparently, whoever built that library either built it as a DAG-specific library or built it with DAG card support.  That means that the library will work only on machines that include Endace's shared library for DAG card support and, obviously, will only be able to capture on a DAG card if the machine has a DAG card.

Do you have Endace's library installed either on the 2.6.2 machine or the 2.7 machine?

**Comment by infrastation** [comment]
Closing as resolved.

**Comment by semkin** [comment]
I was on vacation and didn't reply before. Yes, server where I compiled has DAG card installed and libdag* libraries in /usr/lib64. I compiled the same program in another el6 server (and later edition: 754.23.1 vs 358.23.2) without libdag* libraries and newer libpcap. Successful compilation and successful run in older el6 server(358.23.2). 
Suggestion that it is impact of installed DAG card was correct. Thank you !

**Comment by infrastation** [comment]
If this means DAG support is confirmed broken in libpcap, it might help to spell the steps to reproduce (although this does not necessarily mean there is an easy fix, as RHEL6 with DAG is a rather special kit).

**Comment by guyharris** [comment]
If you build libpcap on a system with the Endace libraries installed, and don't explicitly say `--without-dag` when using the configure script or `-DDISABLE_DAG=YES` when using CMake to prevent DAG card being compiled in, the resulting library will not work on a system without the Endace libraries installed.

The only way to "fix" this would be to have `dag_create()` and `dag_findalldevs()`, as their first action, call a routine that uses `pcap_load_code()` to attempt to load the main Endace library and:

- if that fails, have `dag_create()` return "that's not one of our devices" (because, without the library, there *are* no DAG devices on which libpcap can capture) and have `dag_findalldevs()` not add any devices (for the same reason);
- if that succeeds, get pointers to the required routines using `pcap_find_function()`, and replace all direct calls to functions in the library with calls through the pointers.

This would also involve writing UN\*X versions of `pcap_load_code()` and `pcap_find_function()`, using `dlopen()`, and `dladdr()`.  The routine that calls those functions would also need to use a spinlock or, if possible, a mutex to make sure two threads don't both load the library in parallel.

**Comment by mcr** [comment]
> If you build libpcap on a system with the Endace libraries installed, and don't explicitly say `--without-dag` when using the configure script or `-DDISABLE_DAG=YES` when using CMake to prevent DAG card being compiled in, the resulting library will not work on a system without the Endace libraries installed.

"Doctor! Doctor! It hurts when I poke myself in the eye!"
Doctor: Don't poke yourself in the eye.

**Comment by semkin** [comment]
--without-dag resolved the issue. Thank you all
